name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: apt-get install libusb-1.0-0-dev

    - name: Check Dependencies
      run: make deps

    - name: Linting
      run: make lint

    - name: Formatting
      run: make format

    - name: Build
      run: make

    - name: Test
      run: make test
