name: Build

on:
  push:
    branches: [ "*" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get install -yq libusb-1.0-0-dev

    - name: Check Dependencies
      run: make deps

    - name: Linting
      run: make lint

    - name: Formatting
      run: make format

    - name: Build
      run: make && make usbreset

    - name: Test
      run: make test

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/*